version: '3.8'

networks:
  default:
    name: traefik-default

services:
  nodered:
    container_name: $COMPOSE_PROJECT_NAME
    image: nodered/node-red:latest
    restart: unless-stopped
    volumes:
      - ./volumes/data:/data
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=https"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=1880"